# Generated by Django 4.0 on 2023-09-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsquestions',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups_user', to='auth.Group', verbose_name='Группа отдела'),
        ),
    ]
