# Generated by Django 4.0 on 2023-09-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_group_is_boss_group_is_group_user_is_permits'),
        ('questions', '0002_alter_groupsquestions_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsquestions',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='auth.Group', verbose_name='Группа отдела'),
        ),
    ]
