# Generated by Django 4.0 on 2023-10-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_groupsquestions_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsquestions',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='auth.Group', verbose_name='Группа отдела'),
        ),
    ]
